// Generated by gencpp from file tactile_servo_srvs/choose_configuration_singularity.msg
// DO NOT EDIT!


#ifndef TACTILE_SERVO_SRVS_MESSAGE_CHOOSE_CONFIGURATION_SINGULARITY_H
#define TACTILE_SERVO_SRVS_MESSAGE_CHOOSE_CONFIGURATION_SINGULARITY_H

#include <ros/service_traits.h>


#include <tactile_servo_srvs/choose_configuration_singularityRequest.h>
#include <tactile_servo_srvs/choose_configuration_singularityResponse.h>


namespace tactile_servo_srvs
{

struct choose_configuration_singularity
{

typedef choose_configuration_singularityRequest Request;
typedef choose_configuration_singularityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct choose_configuration_singularity
} // namespace tactile_servo_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tactile_servo_srvs::choose_configuration_singularity > {
  static const char* value()
  {
    return "10ee8dd987888b1b0dd9111a4eae0a74";
  }

  static const char* value(const ::tactile_servo_srvs::choose_configuration_singularity&) { return value(); }
};

template<>
struct DataType< ::tactile_servo_srvs::choose_configuration_singularity > {
  static const char* value()
  {
    return "tactile_servo_srvs/choose_configuration_singularity";
  }

  static const char* value(const ::tactile_servo_srvs::choose_configuration_singularity&) { return value(); }
};


// service_traits::MD5Sum< ::tactile_servo_srvs::choose_configuration_singularityRequest> should match
// service_traits::MD5Sum< ::tactile_servo_srvs::choose_configuration_singularity >
template<>
struct MD5Sum< ::tactile_servo_srvs::choose_configuration_singularityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tactile_servo_srvs::choose_configuration_singularity >::value();
  }
  static const char* value(const ::tactile_servo_srvs::choose_configuration_singularityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tactile_servo_srvs::choose_configuration_singularityRequest> should match
// service_traits::DataType< ::tactile_servo_srvs::choose_configuration_singularity >
template<>
struct DataType< ::tactile_servo_srvs::choose_configuration_singularityRequest>
{
  static const char* value()
  {
    return DataType< ::tactile_servo_srvs::choose_configuration_singularity >::value();
  }
  static const char* value(const ::tactile_servo_srvs::choose_configuration_singularityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tactile_servo_srvs::choose_configuration_singularityResponse> should match
// service_traits::MD5Sum< ::tactile_servo_srvs::choose_configuration_singularity >
template<>
struct MD5Sum< ::tactile_servo_srvs::choose_configuration_singularityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tactile_servo_srvs::choose_configuration_singularity >::value();
  }
  static const char* value(const ::tactile_servo_srvs::choose_configuration_singularityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tactile_servo_srvs::choose_configuration_singularityResponse> should match
// service_traits::DataType< ::tactile_servo_srvs::choose_configuration_singularity >
template<>
struct DataType< ::tactile_servo_srvs::choose_configuration_singularityResponse>
{
  static const char* value()
  {
    return DataType< ::tactile_servo_srvs::choose_configuration_singularity >::value();
  }
  static const char* value(const ::tactile_servo_srvs::choose_configuration_singularityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TACTILE_SERVO_SRVS_MESSAGE_CHOOSE_CONFIGURATION_SINGULARITY_H
