// Generated by gencpp from file tactile_servo_srvs/pose_arm_init.msg
// DO NOT EDIT!


#ifndef TACTILE_SERVO_SRVS_MESSAGE_POSE_ARM_INIT_H
#define TACTILE_SERVO_SRVS_MESSAGE_POSE_ARM_INIT_H

#include <ros/service_traits.h>


#include <tactile_servo_srvs/pose_arm_initRequest.h>
#include <tactile_servo_srvs/pose_arm_initResponse.h>


namespace tactile_servo_srvs
{

struct pose_arm_init
{

typedef pose_arm_initRequest Request;
typedef pose_arm_initResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pose_arm_init
} // namespace tactile_servo_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tactile_servo_srvs::pose_arm_init > {
  static const char* value()
  {
    return "46241584f8d15752cfaafef65fb4333e";
  }

  static const char* value(const ::tactile_servo_srvs::pose_arm_init&) { return value(); }
};

template<>
struct DataType< ::tactile_servo_srvs::pose_arm_init > {
  static const char* value()
  {
    return "tactile_servo_srvs/pose_arm_init";
  }

  static const char* value(const ::tactile_servo_srvs::pose_arm_init&) { return value(); }
};


// service_traits::MD5Sum< ::tactile_servo_srvs::pose_arm_initRequest> should match
// service_traits::MD5Sum< ::tactile_servo_srvs::pose_arm_init >
template<>
struct MD5Sum< ::tactile_servo_srvs::pose_arm_initRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tactile_servo_srvs::pose_arm_init >::value();
  }
  static const char* value(const ::tactile_servo_srvs::pose_arm_initRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tactile_servo_srvs::pose_arm_initRequest> should match
// service_traits::DataType< ::tactile_servo_srvs::pose_arm_init >
template<>
struct DataType< ::tactile_servo_srvs::pose_arm_initRequest>
{
  static const char* value()
  {
    return DataType< ::tactile_servo_srvs::pose_arm_init >::value();
  }
  static const char* value(const ::tactile_servo_srvs::pose_arm_initRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tactile_servo_srvs::pose_arm_initResponse> should match
// service_traits::MD5Sum< ::tactile_servo_srvs::pose_arm_init >
template<>
struct MD5Sum< ::tactile_servo_srvs::pose_arm_initResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tactile_servo_srvs::pose_arm_init >::value();
  }
  static const char* value(const ::tactile_servo_srvs::pose_arm_initResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tactile_servo_srvs::pose_arm_initResponse> should match
// service_traits::DataType< ::tactile_servo_srvs::pose_arm_init >
template<>
struct DataType< ::tactile_servo_srvs::pose_arm_initResponse>
{
  static const char* value()
  {
    return DataType< ::tactile_servo_srvs::pose_arm_init >::value();
  }
  static const char* value(const ::tactile_servo_srvs::pose_arm_initResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TACTILE_SERVO_SRVS_MESSAGE_POSE_ARM_INIT_H
