// Generated by gencpp from file tactile_servo_srvs/select_matrix.msg
// DO NOT EDIT!


#ifndef TACTILE_SERVO_SRVS_MESSAGE_SELECT_MATRIX_H
#define TACTILE_SERVO_SRVS_MESSAGE_SELECT_MATRIX_H

#include <ros/service_traits.h>


#include <tactile_servo_srvs/select_matrixRequest.h>
#include <tactile_servo_srvs/select_matrixResponse.h>


namespace tactile_servo_srvs
{

struct select_matrix
{

typedef select_matrixRequest Request;
typedef select_matrixResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct select_matrix
} // namespace tactile_servo_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tactile_servo_srvs::select_matrix > {
  static const char* value()
  {
    return "477eddf35d1c9126254cd3a55ca19343";
  }

  static const char* value(const ::tactile_servo_srvs::select_matrix&) { return value(); }
};

template<>
struct DataType< ::tactile_servo_srvs::select_matrix > {
  static const char* value()
  {
    return "tactile_servo_srvs/select_matrix";
  }

  static const char* value(const ::tactile_servo_srvs::select_matrix&) { return value(); }
};


// service_traits::MD5Sum< ::tactile_servo_srvs::select_matrixRequest> should match
// service_traits::MD5Sum< ::tactile_servo_srvs::select_matrix >
template<>
struct MD5Sum< ::tactile_servo_srvs::select_matrixRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tactile_servo_srvs::select_matrix >::value();
  }
  static const char* value(const ::tactile_servo_srvs::select_matrixRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tactile_servo_srvs::select_matrixRequest> should match
// service_traits::DataType< ::tactile_servo_srvs::select_matrix >
template<>
struct DataType< ::tactile_servo_srvs::select_matrixRequest>
{
  static const char* value()
  {
    return DataType< ::tactile_servo_srvs::select_matrix >::value();
  }
  static const char* value(const ::tactile_servo_srvs::select_matrixRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tactile_servo_srvs::select_matrixResponse> should match
// service_traits::MD5Sum< ::tactile_servo_srvs::select_matrix >
template<>
struct MD5Sum< ::tactile_servo_srvs::select_matrixResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tactile_servo_srvs::select_matrix >::value();
  }
  static const char* value(const ::tactile_servo_srvs::select_matrixResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tactile_servo_srvs::select_matrixResponse> should match
// service_traits::DataType< ::tactile_servo_srvs::select_matrix >
template<>
struct DataType< ::tactile_servo_srvs::select_matrixResponse>
{
  static const char* value()
  {
    return DataType< ::tactile_servo_srvs::select_matrix >::value();
  }
  static const char* value(const ::tactile_servo_srvs::select_matrixResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TACTILE_SERVO_SRVS_MESSAGE_SELECT_MATRIX_H
