// Generated by gencpp from file tactile_servo_srvs/set_des_feats_srv.msg
// DO NOT EDIT!


#ifndef TACTILE_SERVO_SRVS_MESSAGE_SET_DES_FEATS_SRV_H
#define TACTILE_SERVO_SRVS_MESSAGE_SET_DES_FEATS_SRV_H

#include <ros/service_traits.h>


#include <tactile_servo_srvs/set_des_feats_srvRequest.h>
#include <tactile_servo_srvs/set_des_feats_srvResponse.h>


namespace tactile_servo_srvs
{

struct set_des_feats_srv
{

typedef set_des_feats_srvRequest Request;
typedef set_des_feats_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_des_feats_srv
} // namespace tactile_servo_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tactile_servo_srvs::set_des_feats_srv > {
  static const char* value()
  {
    return "a9f79bb34d45b76c6fd0a8b06fb9504b";
  }

  static const char* value(const ::tactile_servo_srvs::set_des_feats_srv&) { return value(); }
};

template<>
struct DataType< ::tactile_servo_srvs::set_des_feats_srv > {
  static const char* value()
  {
    return "tactile_servo_srvs/set_des_feats_srv";
  }

  static const char* value(const ::tactile_servo_srvs::set_des_feats_srv&) { return value(); }
};


// service_traits::MD5Sum< ::tactile_servo_srvs::set_des_feats_srvRequest> should match
// service_traits::MD5Sum< ::tactile_servo_srvs::set_des_feats_srv >
template<>
struct MD5Sum< ::tactile_servo_srvs::set_des_feats_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tactile_servo_srvs::set_des_feats_srv >::value();
  }
  static const char* value(const ::tactile_servo_srvs::set_des_feats_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tactile_servo_srvs::set_des_feats_srvRequest> should match
// service_traits::DataType< ::tactile_servo_srvs::set_des_feats_srv >
template<>
struct DataType< ::tactile_servo_srvs::set_des_feats_srvRequest>
{
  static const char* value()
  {
    return DataType< ::tactile_servo_srvs::set_des_feats_srv >::value();
  }
  static const char* value(const ::tactile_servo_srvs::set_des_feats_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tactile_servo_srvs::set_des_feats_srvResponse> should match
// service_traits::MD5Sum< ::tactile_servo_srvs::set_des_feats_srv >
template<>
struct MD5Sum< ::tactile_servo_srvs::set_des_feats_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tactile_servo_srvs::set_des_feats_srv >::value();
  }
  static const char* value(const ::tactile_servo_srvs::set_des_feats_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tactile_servo_srvs::set_des_feats_srvResponse> should match
// service_traits::DataType< ::tactile_servo_srvs::set_des_feats_srv >
template<>
struct DataType< ::tactile_servo_srvs::set_des_feats_srvResponse>
{
  static const char* value()
  {
    return DataType< ::tactile_servo_srvs::set_des_feats_srv >::value();
  }
  static const char* value(const ::tactile_servo_srvs::set_des_feats_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TACTILE_SERVO_SRVS_MESSAGE_SET_DES_FEATS_SRV_H
