// Generated by gencpp from file tactile_servo_srvs/start_servo_controller.msg
// DO NOT EDIT!


#ifndef TACTILE_SERVO_SRVS_MESSAGE_START_SERVO_CONTROLLER_H
#define TACTILE_SERVO_SRVS_MESSAGE_START_SERVO_CONTROLLER_H

#include <ros/service_traits.h>


#include <tactile_servo_srvs/start_servo_controllerRequest.h>
#include <tactile_servo_srvs/start_servo_controllerResponse.h>


namespace tactile_servo_srvs
{

struct start_servo_controller
{

typedef start_servo_controllerRequest Request;
typedef start_servo_controllerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct start_servo_controller
} // namespace tactile_servo_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tactile_servo_srvs::start_servo_controller > {
  static const char* value()
  {
    return "e2e21116f5b5b751861cd4a451d33268";
  }

  static const char* value(const ::tactile_servo_srvs::start_servo_controller&) { return value(); }
};

template<>
struct DataType< ::tactile_servo_srvs::start_servo_controller > {
  static const char* value()
  {
    return "tactile_servo_srvs/start_servo_controller";
  }

  static const char* value(const ::tactile_servo_srvs::start_servo_controller&) { return value(); }
};


// service_traits::MD5Sum< ::tactile_servo_srvs::start_servo_controllerRequest> should match
// service_traits::MD5Sum< ::tactile_servo_srvs::start_servo_controller >
template<>
struct MD5Sum< ::tactile_servo_srvs::start_servo_controllerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tactile_servo_srvs::start_servo_controller >::value();
  }
  static const char* value(const ::tactile_servo_srvs::start_servo_controllerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tactile_servo_srvs::start_servo_controllerRequest> should match
// service_traits::DataType< ::tactile_servo_srvs::start_servo_controller >
template<>
struct DataType< ::tactile_servo_srvs::start_servo_controllerRequest>
{
  static const char* value()
  {
    return DataType< ::tactile_servo_srvs::start_servo_controller >::value();
  }
  static const char* value(const ::tactile_servo_srvs::start_servo_controllerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tactile_servo_srvs::start_servo_controllerResponse> should match
// service_traits::MD5Sum< ::tactile_servo_srvs::start_servo_controller >
template<>
struct MD5Sum< ::tactile_servo_srvs::start_servo_controllerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tactile_servo_srvs::start_servo_controller >::value();
  }
  static const char* value(const ::tactile_servo_srvs::start_servo_controllerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tactile_servo_srvs::start_servo_controllerResponse> should match
// service_traits::DataType< ::tactile_servo_srvs::start_servo_controller >
template<>
struct DataType< ::tactile_servo_srvs::start_servo_controllerResponse>
{
  static const char* value()
  {
    return DataType< ::tactile_servo_srvs::start_servo_controller >::value();
  }
  static const char* value(const ::tactile_servo_srvs::start_servo_controllerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TACTILE_SERVO_SRVS_MESSAGE_START_SERVO_CONTROLLER_H
