// Generated by gencpp from file tactile_servo_msgs/AllForce.msg
// DO NOT EDIT!


#ifndef TACTILE_SERVO_MSGS_MESSAGE_ALLFORCE_H
#define TACTILE_SERVO_MSGS_MESSAGE_ALLFORCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace tactile_servo_msgs
{
template <class ContainerAllocator>
struct AllForce_
{
  typedef AllForce_<ContainerAllocator> Type;

  AllForce_()
    : header()
    , real(0.0)
    , desired(0.0)
    , weiss(0.0)  {
    }
  AllForce_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , real(0.0)
    , desired(0.0)
    , weiss(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _real_type;
  _real_type real;

   typedef double _desired_type;
  _desired_type desired;

   typedef double _weiss_type;
  _weiss_type weiss;





  typedef boost::shared_ptr< ::tactile_servo_msgs::AllForce_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tactile_servo_msgs::AllForce_<ContainerAllocator> const> ConstPtr;

}; // struct AllForce_

typedef ::tactile_servo_msgs::AllForce_<std::allocator<void> > AllForce;

typedef boost::shared_ptr< ::tactile_servo_msgs::AllForce > AllForcePtr;
typedef boost::shared_ptr< ::tactile_servo_msgs::AllForce const> AllForceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tactile_servo_msgs::AllForce_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tactile_servo_msgs::AllForce_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tactile_servo_msgs::AllForce_<ContainerAllocator1> & lhs, const ::tactile_servo_msgs::AllForce_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.real == rhs.real &&
    lhs.desired == rhs.desired &&
    lhs.weiss == rhs.weiss;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tactile_servo_msgs::AllForce_<ContainerAllocator1> & lhs, const ::tactile_servo_msgs::AllForce_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tactile_servo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tactile_servo_msgs::AllForce_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tactile_servo_msgs::AllForce_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tactile_servo_msgs::AllForce_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tactile_servo_msgs::AllForce_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tactile_servo_msgs::AllForce_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tactile_servo_msgs::AllForce_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tactile_servo_msgs::AllForce_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef1fc02563dc2cf330e05b255f81bf87";
  }

  static const char* value(const ::tactile_servo_msgs::AllForce_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef1fc02563dc2cf3ULL;
  static const uint64_t static_value2 = 0x30e05b255f81bf87ULL;
};

template<class ContainerAllocator>
struct DataType< ::tactile_servo_msgs::AllForce_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tactile_servo_msgs/AllForce";
  }

  static const char* value(const ::tactile_servo_msgs::AllForce_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tactile_servo_msgs::AllForce_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 real\n"
"float64 desired\n"
"float64 weiss\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::tactile_servo_msgs::AllForce_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tactile_servo_msgs::AllForce_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.real);
      stream.next(m.desired);
      stream.next(m.weiss);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AllForce_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tactile_servo_msgs::AllForce_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tactile_servo_msgs::AllForce_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "real: ";
    Printer<double>::stream(s, indent + "  ", v.real);
    s << indent << "desired: ";
    Printer<double>::stream(s, indent + "  ", v.desired);
    s << indent << "weiss: ";
    Printer<double>::stream(s, indent + "  ", v.weiss);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TACTILE_SERVO_MSGS_MESSAGE_ALLFORCE_H
