// Generated by gencpp from file tactile_servo_msgs/ContsFeats.msg
// DO NOT EDIT!


#ifndef TACTILE_SERVO_MSGS_MESSAGE_CONTSFEATS_H
#define TACTILE_SERVO_MSGS_MESSAGE_CONTSFEATS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <tactile_servo_msgs/OneContFeats.h>

namespace tactile_servo_msgs
{
template <class ContainerAllocator>
struct ContsFeats_
{
  typedef ContsFeats_<ContainerAllocator> Type;

  ContsFeats_()
    : header()
    , control_features()  {
    }
  ContsFeats_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , control_features(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::tactile_servo_msgs::OneContFeats_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::tactile_servo_msgs::OneContFeats_<ContainerAllocator> >::other >  _control_features_type;
  _control_features_type control_features;





  typedef boost::shared_ptr< ::tactile_servo_msgs::ContsFeats_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tactile_servo_msgs::ContsFeats_<ContainerAllocator> const> ConstPtr;

}; // struct ContsFeats_

typedef ::tactile_servo_msgs::ContsFeats_<std::allocator<void> > ContsFeats;

typedef boost::shared_ptr< ::tactile_servo_msgs::ContsFeats > ContsFeatsPtr;
typedef boost::shared_ptr< ::tactile_servo_msgs::ContsFeats const> ContsFeatsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tactile_servo_msgs::ContsFeats_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tactile_servo_msgs::ContsFeats_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tactile_servo_msgs::ContsFeats_<ContainerAllocator1> & lhs, const ::tactile_servo_msgs::ContsFeats_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.control_features == rhs.control_features;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tactile_servo_msgs::ContsFeats_<ContainerAllocator1> & lhs, const ::tactile_servo_msgs::ContsFeats_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tactile_servo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tactile_servo_msgs::ContsFeats_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tactile_servo_msgs::ContsFeats_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tactile_servo_msgs::ContsFeats_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tactile_servo_msgs::ContsFeats_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tactile_servo_msgs::ContsFeats_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tactile_servo_msgs::ContsFeats_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tactile_servo_msgs::ContsFeats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "44c38b3dcf679267b4ec9aa49b84b60d";
  }

  static const char* value(const ::tactile_servo_msgs::ContsFeats_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x44c38b3dcf679267ULL;
  static const uint64_t static_value2 = 0xb4ec9aa49b84b60dULL;
};

template<class ContainerAllocator>
struct DataType< ::tactile_servo_msgs::ContsFeats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tactile_servo_msgs/ContsFeats";
  }

  static const char* value(const ::tactile_servo_msgs::ContsFeats_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tactile_servo_msgs::ContsFeats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header                                   # stamp\n"
"tactile_servo_msgs/OneContFeats[] control_features           # array of contacts\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: tactile_servo_msgs/OneContFeats\n"
"float64 centerpressure_x\n"
"float64 centerpressure_y\n"
"float64 contactForce\n"
"float64 centerContact_x\n"
"float64 centerContact_y\n"
"float64 contactOrientation\n"
"float64 zmp_x\n"
"float64 zmp_y\n"
"bool is_contact\n"
"int32 num_pixels_contact\n"
"float64 highest_force_cell\n"
"float64 real_total_force\n"
"\n"
;
  }

  static const char* value(const ::tactile_servo_msgs::ContsFeats_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tactile_servo_msgs::ContsFeats_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.control_features);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ContsFeats_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tactile_servo_msgs::ContsFeats_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tactile_servo_msgs::ContsFeats_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "control_features[]" << std::endl;
    for (size_t i = 0; i < v.control_features.size(); ++i)
    {
      s << indent << "  control_features[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::tactile_servo_msgs::OneContFeats_<ContainerAllocator> >::stream(s, indent + "    ", v.control_features[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TACTILE_SERVO_MSGS_MESSAGE_CONTSFEATS_H
