# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tactile_servo_msgs/CalibWeissNano.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class CalibWeissNano(genpy.Message):
  _md5sum = "427d9e81487d12d71f0577b073eb48de"
  _type = "tactile_servo_msgs/CalibWeissNano"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
float64 contactForce
float64 zmp_x
float64 zmp_y
float64 cop_x
float64 cop_y
float64 orient_z
float64 coc_x
float64 coc_y
geometry_msgs/Wrench nano
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Wrench
# This represents force in free space, separated into
# its linear and angular parts.
Vector3  force
Vector3  torque

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['header','contactForce','zmp_x','zmp_y','cop_x','cop_y','orient_z','coc_x','coc_y','nano']
  _slot_types = ['std_msgs/Header','float64','float64','float64','float64','float64','float64','float64','float64','geometry_msgs/Wrench']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,contactForce,zmp_x,zmp_y,cop_x,cop_y,orient_z,coc_x,coc_y,nano

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CalibWeissNano, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.contactForce is None:
        self.contactForce = 0.
      if self.zmp_x is None:
        self.zmp_x = 0.
      if self.zmp_y is None:
        self.zmp_y = 0.
      if self.cop_x is None:
        self.cop_x = 0.
      if self.cop_y is None:
        self.cop_y = 0.
      if self.orient_z is None:
        self.orient_z = 0.
      if self.coc_x is None:
        self.coc_x = 0.
      if self.coc_y is None:
        self.coc_y = 0.
      if self.nano is None:
        self.nano = geometry_msgs.msg.Wrench()
    else:
      self.header = std_msgs.msg.Header()
      self.contactForce = 0.
      self.zmp_x = 0.
      self.zmp_y = 0.
      self.cop_x = 0.
      self.cop_y = 0.
      self.orient_z = 0.
      self.coc_x = 0.
      self.coc_y = 0.
      self.nano = geometry_msgs.msg.Wrench()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_14d().pack(_x.contactForce, _x.zmp_x, _x.zmp_y, _x.cop_x, _x.cop_y, _x.orient_z, _x.coc_x, _x.coc_y, _x.nano.force.x, _x.nano.force.y, _x.nano.force.z, _x.nano.torque.x, _x.nano.torque.y, _x.nano.torque.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.nano is None:
        self.nano = geometry_msgs.msg.Wrench()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 112
      (_x.contactForce, _x.zmp_x, _x.zmp_y, _x.cop_x, _x.cop_y, _x.orient_z, _x.coc_x, _x.coc_y, _x.nano.force.x, _x.nano.force.y, _x.nano.force.z, _x.nano.torque.x, _x.nano.torque.y, _x.nano.torque.z,) = _get_struct_14d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_14d().pack(_x.contactForce, _x.zmp_x, _x.zmp_y, _x.cop_x, _x.cop_y, _x.orient_z, _x.coc_x, _x.coc_y, _x.nano.force.x, _x.nano.force.y, _x.nano.force.z, _x.nano.torque.x, _x.nano.torque.y, _x.nano.torque.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.nano is None:
        self.nano = geometry_msgs.msg.Wrench()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 112
      (_x.contactForce, _x.zmp_x, _x.zmp_y, _x.cop_x, _x.cop_y, _x.orient_z, _x.coc_x, _x.coc_y, _x.nano.force.x, _x.nano.force.y, _x.nano.force.z, _x.nano.torque.x, _x.nano.torque.y, _x.nano.torque.z,) = _get_struct_14d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_14d = None
def _get_struct_14d():
    global _struct_14d
    if _struct_14d is None:
        _struct_14d = struct.Struct("<14d")
    return _struct_14d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
