(cl:in-package tactile_servo_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          A0-VAL
          A0
          A1-VAL
          A1
          A2-VAL
          A2
          A3-VAL
          A3
          A4-VAL
          A4
          A5-VAL
          A5
          A6-VAL
          A6
          A7-VAL
          A7
          A8-VAL
          A8
          A9-VAL
          A9
          A10-VAL
          A10
          A11-VAL
          A11
          A12-VAL
          A12
          A13-VAL
          A13
          A14-VAL
          A14
          A15-VAL
          A15
))