(cl:in-package tactile_servo_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          FX-VAL
          FX
          FY-VAL
          FY
          FZ-VAL
          FZ
          FWX-VAL
          FWX
          FWY-VAL
          FWY
          FWZ-VAL
          FWZ
          COC_X-VAL
          COC_X
          COC_Y-VAL
          COC_Y
          F-VAL
          F
          ZMP_X-VAL
          ZMP_X
          ZMP_Y-VAL
          ZMP_Y
          ORIENT_Z-VAL
          ORIENT_Z
          COP_X-VAL
          COP_X
          COP_Y-VAL
          COP_Y
          COC_XD-VAL
          COC_XD
          COC_YD-VAL
          COC_YD
          FD-VAL
          FD
          ZMP_XD-VAL
          ZMP_XD
          ZMP_YD-VAL
          ZMP_YD
          ORIENT_ZD-VAL
          ORIENT_ZD
          COP_XD-VAL
          COP_XD
          COP_YD-VAL
          COP_YD
          NUM_CONTOURS-VAL
          NUM_CONTOURS
          X_NOW-VAL
          X_NOW
          Y_NOW-VAL
          Y_NOW
          Z_NOW-VAL
          Z_NOW
          WX_NOW-VAL
          WX_NOW
          WY_NOW-VAL
          WY_NOW
          WZ_NOW-VAL
          WZ_NOW
          WW_NOW-VAL
          WW_NOW
          X_DES-VAL
          X_DES
          Y_DES-VAL
          Y_DES
          Z_DES-VAL
          Z_DES
          WX_DES-VAL
          WX_DES
          WY_DES-VAL
          WY_DES
          WZ_DES-VAL
          WZ_DES
          WW_DES-VAL
          WW_DES
          X_C-VAL
          X_C
          Y_C-VAL
          Y_C
          Z_C-VAL
          Z_C
          DT-VAL
          DT
          TIME-VAL
          TIME
          TEST_TIME2-VAL
          TEST_TIME2
          IMG-VAL
          IMG
          IS_IN_CONTACT_UR-VAL
          IS_IN_CONTACT_UR
          PIXELS_IN_CONTACT_UR-VAL
          PIXELS_IN_CONTACT_UR
          HIGHEST_FORCE_CELL_UR-VAL
          HIGHEST_FORCE_CELL_UR
          REAL_TOTAL_FORCE_UR-VAL
          REAL_TOTAL_FORCE_UR
          CURRENT_STATE_UR-VAL
          CURRENT_STATE_UR
          JOINT_ANGLES-VAL
          JOINT_ANGLES
          JOINT_EFFORTS-VAL
          JOINT_EFFORTS
          X_C1-VAL
          X_C1
          Y_C1-VAL
          Y_C1
          Z_C1-VAL
          Z_C1
          X_C2-VAL
          X_C2
          Y_C2-VAL
          Y_C2
          Z_C2-VAL
          Z_C2
          X_C3-VAL
          X_C3
          Y_C3-VAL
          Y_C3
          Z_C3-VAL
          Z_C3
          X_C4-VAL
          X_C4
          Y_C4-VAL
          Y_C4
          Z_C4-VAL
          Z_C4
          X_C5-VAL
          X_C5
          Y_C5-VAL
          Y_C5
          Z_C5-VAL
          Z_C5
          X_C6-VAL
          X_C6
          Y_C6-VAL
          Y_C6
          Z_C6-VAL
          Z_C6
          X_C7-VAL
          X_C7
          Y_C7-VAL
          Y_C7
          Z_C7-VAL
          Z_C7
          X_C8-VAL
          X_C8
          Y_C8-VAL
          Y_C8
          Z_C8-VAL
          Z_C8
          X_C9-VAL
          X_C9
          Y_C9-VAL
          Y_C9
          Z_C9-VAL
          Z_C9
          X_C10-VAL
          X_C10
          Y_C10-VAL
          Y_C10
          Z_C10-VAL
          Z_C10
          X_C11-VAL
          X_C11
          Y_C11-VAL
          Y_C11
          Z_C11-VAL
          Z_C11
          X_C12-VAL
          X_C12
          Y_C12-VAL
          Y_C12
          Z_C12-VAL
          Z_C12
          X_C13-VAL
          X_C13
          Y_C13-VAL
          Y_C13
          Z_C13-VAL
          Z_C13
          X_C14-VAL
          X_C14
          Y_C14-VAL
          Y_C14
          Z_C14-VAL
          Z_C14
          X_C15-VAL
          X_C15
          Y_C15-VAL
          Y_C15
          Z_C15-VAL
          Z_C15
))