(cl:in-package tactile_servo_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          FX-VAL
          FX
          FY-VAL
          FY
          FZ-VAL
          FZ
          FWX-VAL
          FWX
          FWY-VAL
          FWY
          FWZ-VAL
          FWZ
          COC_X-VAL
          COC_X
          COC_Y-VAL
          COC_Y
          FAREA-VAL
          FAREA
          ISCONTACT-VAL
          ISCONTACT
          F-VAL
          F
          ZMP_X-VAL
          ZMP_X
          ZMP_Y-VAL
          ZMP_Y
          ORIENT_Z-VAL
          ORIENT_Z
          COP_X-VAL
          COP_X
          COP_Y-VAL
          COP_Y
          COC_XD-VAL
          COC_XD
          COC_YD-VAL
          COC_YD
          FD-VAL
          FD
          ZMP_XD-VAL
          ZMP_XD
          ZMP_YD-VAL
          ZMP_YD
          ORIENT_ZD-VAL
          ORIENT_ZD
          COP_XD-VAL
          COP_XD
          COP_YD-VAL
          COP_YD
          NUM_CONTOURS-VAL
          NUM_CONTOURS
          X_NOW-VAL
          X_NOW
          Y_NOW-VAL
          Y_NOW
          Z_NOW-VAL
          Z_NOW
          WX_NOW-VAL
          WX_NOW
          WY_NOW-VAL
          WY_NOW
          WZ_NOW-VAL
          WZ_NOW
          WW_NOW-VAL
          WW_NOW
          X_DES-VAL
          X_DES
          Y_DES-VAL
          Y_DES
          Z_DES-VAL
          Z_DES
          WX_DES-VAL
          WX_DES
          WY_DES-VAL
          WY_DES
          WZ_DES-VAL
          WZ_DES
          WW_DES-VAL
          WW_DES
          X_C-VAL
          X_C
          Y_C-VAL
          Y_C
          Z_C-VAL
          Z_C
          DT-VAL
          DT
          TIME-VAL
          TIME
          TEST_TIME2-VAL
          TEST_TIME2
))