//#line 2 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the tactile_servo_config package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __tactile_servo_config__IMG_PROC_PARAMSCONFIG_H__
#define __tactile_servo_config__IMG_PROC_PARAMSCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace tactile_servo_config
{
  class img_proc_paramsConfigStatics;

  class img_proc_paramsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(img_proc_paramsConfig &config, const img_proc_paramsConfig &max, const img_proc_paramsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const img_proc_paramsConfig &config1, const img_proc_paramsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, img_proc_paramsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const img_proc_paramsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, img_proc_paramsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const img_proc_paramsConfig &config) const = 0;
      virtual void getValue(const img_proc_paramsConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T img_proc_paramsConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T img_proc_paramsConfig::* field;

      virtual void clamp(img_proc_paramsConfig &config, const img_proc_paramsConfig &max, const img_proc_paramsConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const img_proc_paramsConfig &config1, const img_proc_paramsConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, img_proc_paramsConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const img_proc_paramsConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, img_proc_paramsConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const img_proc_paramsConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const img_proc_paramsConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, img_proc_paramsConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, img_proc_paramsConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<img_proc_paramsConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(img_proc_paramsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("noise_threshold"==(*_i)->name){noise_threshold = boost::any_cast<int>(val);}
        if("coc_threshold"==(*_i)->name){coc_threshold = boost::any_cast<int>(val);}
        if("pres_from_image"==(*_i)->name){pres_from_image = boost::any_cast<double>(val);}
        if("force_from_area"==(*_i)->name){force_from_area = boost::any_cast<double>(val);}
        if("torque_from_image_y"==(*_i)->name){torque_from_image_y = boost::any_cast<double>(val);}
        if("torque_from_image_x"==(*_i)->name){torque_from_image_x = boost::any_cast<double>(val);}
        if("compare_eigens"==(*_i)->name){compare_eigens = boost::any_cast<int>(val);}
        if("filter_length"==(*_i)->name){filter_length = boost::any_cast<double>(val);}
        if("coc2zmp_begin_num_pixels"==(*_i)->name){coc2zmp_begin_num_pixels = boost::any_cast<int>(val);}
        if("coc2zmp_end_num_pixels"==(*_i)->name){coc2zmp_end_num_pixels = boost::any_cast<int>(val);}
        if("coc2zmp_pixels2smoothtrans"==(*_i)->name){coc2zmp_pixels2smoothtrans = boost::any_cast<double>(val);}
        if("improc_bin_thresh"==(*_i)->name){improc_bin_thresh = boost::any_cast<int>(val);}
        if("improc_filter_length_features"==(*_i)->name){improc_filter_length_features = boost::any_cast<int>(val);}
        if("find_contour_mode_name"==(*_i)->name){find_contour_mode_name = boost::any_cast<std::string>(val);}
        if("find_contour_method_name"==(*_i)->name){find_contour_method_name = boost::any_cast<std::string>(val);}
        if("improc_approx_epsilon"==(*_i)->name){improc_approx_epsilon = boost::any_cast<double>(val);}
        if("force_scale"==(*_i)->name){force_scale = boost::any_cast<double>(val);}
        if("improc_area_thresh"==(*_i)->name){improc_area_thresh = boost::any_cast<int>(val);}
        if("improc_scaling_factor"==(*_i)->name){improc_scaling_factor = boost::any_cast<int>(val);}
      }
    }

    int noise_threshold;
int coc_threshold;
double pres_from_image;
double force_from_area;
double torque_from_image_y;
double torque_from_image_x;
int compare_eigens;
double filter_length;
int coc2zmp_begin_num_pixels;
int coc2zmp_end_num_pixels;
double coc2zmp_pixels2smoothtrans;
int improc_bin_thresh;
int improc_filter_length_features;
std::string find_contour_mode_name;
std::string find_contour_method_name;
double improc_approx_epsilon;
double force_scale;
int improc_area_thresh;
int improc_scaling_factor;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int noise_threshold;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int coc_threshold;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pres_from_image;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double force_from_area;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double torque_from_image_y;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double torque_from_image_x;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int compare_eigens;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double filter_length;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int coc2zmp_begin_num_pixels;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int coc2zmp_end_num_pixels;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double coc2zmp_pixels2smoothtrans;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int improc_bin_thresh;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int improc_filter_length_features;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string find_contour_mode_name;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string find_contour_method_name;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double improc_approx_epsilon;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double force_scale;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int improc_area_thresh;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int improc_scaling_factor;
//#line 228 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("img_proc_paramsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const img_proc_paramsConfig &__max__ = __getMax__();
      const img_proc_paramsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const img_proc_paramsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const img_proc_paramsConfig &__getDefault__();
    static const img_proc_paramsConfig &__getMax__();
    static const img_proc_paramsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const img_proc_paramsConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void img_proc_paramsConfig::ParamDescription<std::string>::clamp(img_proc_paramsConfig &config, const img_proc_paramsConfig &max, const img_proc_paramsConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class img_proc_paramsConfigStatics
  {
    friend class img_proc_paramsConfig;

    img_proc_paramsConfigStatics()
    {
img_proc_paramsConfig::GroupDescription<img_proc_paramsConfig::DEFAULT, img_proc_paramsConfig> Default("Default", "", 0, 0, true, &img_proc_paramsConfig::groups);
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.noise_threshold = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.noise_threshold = 255;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.noise_threshold = 10;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<int>("noise_threshold", "int", 0, "threshold to binarize image", "", &img_proc_paramsConfig::noise_threshold)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<int>("noise_threshold", "int", 0, "threshold to binarize image", "", &img_proc_paramsConfig::noise_threshold)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.coc_threshold = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.coc_threshold = 255;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.coc_threshold = 10;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<int>("coc_threshold", "int", 0, "coc_threshold", "", &img_proc_paramsConfig::coc_threshold)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<int>("coc_threshold", "int", 0, "coc_threshold", "", &img_proc_paramsConfig::coc_threshold)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pres_from_image = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pres_from_image = 999999999.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pres_from_image = 27.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<double>("pres_from_image", "double", 0, "pres_from_image", "", &img_proc_paramsConfig::pres_from_image)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<double>("pres_from_image", "double", 0, "pres_from_image", "", &img_proc_paramsConfig::pres_from_image)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.force_from_area = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.force_from_area = 999999999.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.force_from_area = 20000.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<double>("force_from_area", "double", 0, "force", "", &img_proc_paramsConfig::force_from_area)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<double>("force_from_area", "double", 0, "force", "", &img_proc_paramsConfig::force_from_area)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.torque_from_image_y = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.torque_from_image_y = 999999999.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.torque_from_image_y = 25.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<double>("torque_from_image_y", "double", 0, "torque_from_image_y", "", &img_proc_paramsConfig::torque_from_image_y)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<double>("torque_from_image_y", "double", 0, "torque_from_image_y", "", &img_proc_paramsConfig::torque_from_image_y)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.torque_from_image_x = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.torque_from_image_x = 999999999.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.torque_from_image_x = 25.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<double>("torque_from_image_x", "double", 0, "torque_from_image_x", "", &img_proc_paramsConfig::torque_from_image_x)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<double>("torque_from_image_x", "double", 0, "torque_from_image_x", "", &img_proc_paramsConfig::torque_from_image_x)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.compare_eigens = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.compare_eigens = 255;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.compare_eigens = 5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<int>("compare_eigens", "int", 0, "compare_eigens", "", &img_proc_paramsConfig::compare_eigens)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<int>("compare_eigens", "int", 0, "compare_eigens", "", &img_proc_paramsConfig::compare_eigens)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.filter_length = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.filter_length = 100.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.filter_length = 15.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<double>("filter_length", "double", 0, "filter_feats", "", &img_proc_paramsConfig::filter_length)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<double>("filter_length", "double", 0, "filter_feats", "", &img_proc_paramsConfig::filter_length)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.coc2zmp_begin_num_pixels = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.coc2zmp_begin_num_pixels = 84;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.coc2zmp_begin_num_pixels = 7;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<int>("coc2zmp_begin_num_pixels", "int", 0, "No pix to begin to smooth trans", "", &img_proc_paramsConfig::coc2zmp_begin_num_pixels)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<int>("coc2zmp_begin_num_pixels", "int", 0, "No pix to begin to smooth trans", "", &img_proc_paramsConfig::coc2zmp_begin_num_pixels)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.coc2zmp_end_num_pixels = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.coc2zmp_end_num_pixels = 84;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.coc2zmp_end_num_pixels = 15;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<int>("coc2zmp_end_num_pixels", "int", 0, "No pix to end to smooth trans", "", &img_proc_paramsConfig::coc2zmp_end_num_pixels)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<int>("coc2zmp_end_num_pixels", "int", 0, "No pix to end to smooth trans", "", &img_proc_paramsConfig::coc2zmp_end_num_pixels)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.coc2zmp_pixels2smoothtrans = -9999.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.coc2zmp_pixels2smoothtrans = 9999.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.coc2zmp_pixels2smoothtrans = 0.025;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<double>("coc2zmp_pixels2smoothtrans", "double", 0, "for scaling No_pix to smooth", "", &img_proc_paramsConfig::coc2zmp_pixels2smoothtrans)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<double>("coc2zmp_pixels2smoothtrans", "double", 0, "for scaling No_pix to smooth", "", &img_proc_paramsConfig::coc2zmp_pixels2smoothtrans)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.improc_bin_thresh = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.improc_bin_thresh = 255;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.improc_bin_thresh = 10;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<int>("improc_bin_thresh", "int", 0, "binarize", "", &img_proc_paramsConfig::improc_bin_thresh)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<int>("improc_bin_thresh", "int", 0, "binarize", "", &img_proc_paramsConfig::improc_bin_thresh)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.improc_filter_length_features = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.improc_filter_length_features = 255;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.improc_filter_length_features = 30;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<int>("improc_filter_length_features", "int", 0, "filter_length_features", "", &img_proc_paramsConfig::improc_filter_length_features)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<int>("improc_filter_length_features", "int", 0, "filter_length_features", "", &img_proc_paramsConfig::improc_filter_length_features)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.find_contour_mode_name = "";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.find_contour_mode_name = "";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.find_contour_mode_name = "CV_RETR_EXTERNAL";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<std::string>("find_contour_mode_name", "str", 0, "Contour retrieval mode:CV_RETR_EXTERNAL,CV_RETR_LIST,CV_RETR_CCOMP,CV_RETR_TREE", "", &img_proc_paramsConfig::find_contour_mode_name)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<std::string>("find_contour_mode_name", "str", 0, "Contour retrieval mode:CV_RETR_EXTERNAL,CV_RETR_LIST,CV_RETR_CCOMP,CV_RETR_TREE", "", &img_proc_paramsConfig::find_contour_mode_name)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.find_contour_method_name = "";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.find_contour_method_name = "";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.find_contour_method_name = "CV_CHAIN_APPROX_SIMPLE";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<std::string>("find_contour_method_name", "str", 0, "Contour approximation method:CV_CHAIN_APPROX_NONE,CV_CHAIN_APPROX_SIMPLE", "", &img_proc_paramsConfig::find_contour_method_name)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<std::string>("find_contour_method_name", "str", 0, "Contour approximation method:CV_CHAIN_APPROX_NONE,CV_CHAIN_APPROX_SIMPLE", "", &img_proc_paramsConfig::find_contour_method_name)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.improc_approx_epsilon = 0.01;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.improc_approx_epsilon = 10000.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.improc_approx_epsilon = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<double>("improc_approx_epsilon", "double", 0, "Parameter specifying the approximation accuracy. This is the maximum distance between the original curve and its approximation.", "", &img_proc_paramsConfig::improc_approx_epsilon)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<double>("improc_approx_epsilon", "double", 0, "Parameter specifying the approximation accuracy. This is the maximum distance between the original curve and its approximation.", "", &img_proc_paramsConfig::improc_approx_epsilon)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.force_scale = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.force_scale = 999999999.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.force_scale = 20000.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<double>("force_scale", "double", 0, "force_scale", "", &img_proc_paramsConfig::force_scale)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<double>("force_scale", "double", 0, "force_scale", "", &img_proc_paramsConfig::force_scale)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.improc_area_thresh = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.improc_area_thresh = 2000;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.improc_area_thresh = 14;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<int>("improc_area_thresh", "int", 0, "threshold for contact area", "", &img_proc_paramsConfig::improc_area_thresh)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<int>("improc_area_thresh", "int", 0, "threshold for contact area", "", &img_proc_paramsConfig::improc_area_thresh)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.improc_scaling_factor = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.improc_scaling_factor = 2000;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.improc_scaling_factor = 30;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<int>("improc_scaling_factor", "int", 0, "scaling_factor", "", &img_proc_paramsConfig::improc_scaling_factor)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(img_proc_paramsConfig::AbstractParamDescriptionConstPtr(new img_proc_paramsConfig::ParamDescription<int>("improc_scaling_factor", "int", 0, "scaling_factor", "", &img_proc_paramsConfig::improc_scaling_factor)));
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(img_proc_paramsConfig::AbstractGroupDescriptionConstPtr(new img_proc_paramsConfig::GroupDescription<img_proc_paramsConfig::DEFAULT, img_proc_paramsConfig>(Default)));
//#line 366 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<img_proc_paramsConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<img_proc_paramsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<img_proc_paramsConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    img_proc_paramsConfig __max__;
    img_proc_paramsConfig __min__;
    img_proc_paramsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const img_proc_paramsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static img_proc_paramsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &img_proc_paramsConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const img_proc_paramsConfig &img_proc_paramsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const img_proc_paramsConfig &img_proc_paramsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const img_proc_paramsConfig &img_proc_paramsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<img_proc_paramsConfig::AbstractParamDescriptionConstPtr> &img_proc_paramsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<img_proc_paramsConfig::AbstractGroupDescriptionConstPtr> &img_proc_paramsConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const img_proc_paramsConfigStatics *img_proc_paramsConfig::__get_statics__()
  {
    const static img_proc_paramsConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = img_proc_paramsConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __IMG_PROC_PARAMSRECONFIGURATOR_H__
